# Generated by Django 6.0.1 on 2026-01-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('NOW', 'À l’affiche'), ('SOON', 'Prochainement')], default='NOW', max_length=4)),
                ('external_id', models.CharField(blank=True, help_text='ID du film depuis une API externe (ex: TMDb)', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='films', to='cinema.genre')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilmCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=120)),
                ('billing_order', models.PositiveSmallIntegerField(default=0)),
                ('is_main', models.BooleanField(default=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.film')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.person')),
            ],
            options={
                'verbose_name': 'Casting',
                'verbose_name_plural': 'Casting',
                'ordering': ['film', 'billing_order', 'person__name'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='films', through='cinema.FilmCast', to='cinema.person'),
        ),
        migrations.AddConstraint(
            model_name='filmcast',
            constraint=models.UniqueConstraint(fields=('film', 'person'), name='unique_person_per_film'),
        ),
    ]
