# Generated by Django 6.0.1 on 2026-01-29 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('language', models.CharField(blank=True, help_text='Ex: VF, VOSTFR', max_length=10)),
                ('format', models.CharField(blank=True, help_text='Ex: 2D, 3D, IMAX', max_length=10)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='cinema.film')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='cinema.salle')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['starts_at'],
            },
        ),
    ]
