# Generated by Django 6.0.1 on 2026-01-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_salle_film_trailer_url_seance'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
