# Generated by Django 6.0.1 on 2026-01-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_seance_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('NOW', 'À l’affiche'), ('SOON', 'Prochainement'), ('ARCH', 'Archivé')], default='SOON', editable=False, max_length=4),
        ),
    ]
