# Generated by Django 6.0.1 on 2026-01-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_film_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='format',
            field=models.CharField(blank=True, choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX'), ('DOLBY', 'DOLBY')], default='2D', max_length=10),
        ),
        migrations.AlterField(
            model_name='seance',
            name='language',
            field=models.CharField(choices=[('VF', 'VF'), ('VOSTFR', 'VOSTFR')], default='VF', max_length=10),
        ),
    ]
