# Generated by Django 6.0.1 on 2026-01-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_seance_format_alter_seance_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
